### ISSUE TITLE
How to clear storage in jest tests?

### ISSUE THREAD

**Issue by danbruegge** [donavon/use-persisted-state#12]
Hi,
i discovered that using `window.localStorage.clear()` in `beforeEach` has no effect in jest tests. Tried also `global` instead of `window`.

https://codesandbox.io/s/2o1ljwjwy0

All test should work because i only click once.

How can i reset the storage for each test?

**Comment by bmds** [comment]
Also running into this when using https://github.com/clarkbw/jest-localstorage-mock

**Comment by enzoferey** [comment]
As this shows up as second result on google search for "jest clear local storage", it works for me via:

```typescript
beforeEach(() => {
    window.localStorage.clear();
});
```
