### ISSUE TITLE
Is it safe to use createPersistedState within the same functional component as the calling component?

### ISSUE THREAD

**Issue by charlex** [donavon/use-persisted-state#13]
For instance, is this safe? 

```jsx
export const MyComp = ({ myKey }) => {
  const usePrefState = createPersistedState(
    `prefix:${myKey}`
  );
  const [show, toggle] = usePrefState(0);

  return (
```

By "safe" I mean: 

- This approach results in about the same number of read/write operations
- This approach will not result in any unintended consequences, such as performance issues or data loss due to re-renders.

--

Note: As I was typing up this question, I decided to try an approach with `useMemo` that would limit the concern. **I'll go ahead and leave the above section just for reference, and leave the below code snippet for those with the same question:**

```jsx
export const MyComp = ({ myKey }) => {
  const usePrefState = useMemo(() => createPersistedState(
    `prefix:${myKey}`, []
  ));
  const [show, toggle] = usePrefState(0);

  return (
```

**Comment by karlhorky** [comment]
@charlex Did that work for you like that? I think there are some issues:

- closing parenthesis is at the wrong position in the code
- dependencies array is empty (it should have `myKey` in it)

Updated version:

```js
export const MyComp = ({ myKey }) => {
  const usePrefState = useMemo(
	() => createPersistedState(`prefix:${myKey}`),
	[myKey]
  );
  const [show, toggle] = usePrefState(0);

  return (
```
