### ISSUE TITLE
New state isn't persisted if component is hidden before next render

### ISSUE THREAD

**Issue by mungojam** [donavon/use-persisted-state#18]
If a component is removed right after setting a new persisted value, the value is never set. It looks like this is because `setState` from `useState` is being returned directly. The updated state never gets seen because the component doesn't re-render. That would be fine with a vanilla `useState`, but isn't when you are using persistent state.

 https://github.com/donavon/use-persisted-state/blob/beb9458a5e2144d8f50bd33dbf17429eff1316ec/src/usePersistedState.js#L42

I think the fix is to return a wrapped `setState` function and force the value to be persisted when it is called rather than relying purely on `state` changing which it doesn't in this case.

Here is a reproducible example. The 'Increment' button works but the 'Increment and Hide' does not.

```jsx
import React, { useState } from 'react';
import ReactDOM from 'react-dom';

import createPersistedState from 'use-persisted-state';

const useCounterState = createPersistedState('count');

const useCounter = initialCount => {
    const [count, setCount] = useCounterState(initialCount);

    return {
        count,
        increment: () => setCount(currentCount => currentCount + 1)
    };
};


const App = () => {
    const { count } = useCounter(1);
    const [showIncrement, setShowIncrement] = useState(true);

    let ComponentToShow;
    if (showIncrement) {
        ComponentToShow = () => <IncrementComponent close={() => setShowIncrement(false)} />;
    } else {
        ComponentToShow = () => <button onClick={() => setShowIncrement(true)}>Show Again</button>;
    }

    return <div>
        <div>count is {count}</div>
        <ComponentToShow />
    </div>
};

const IncrementComponent = ({ close }) => {
    const { increment } = useCounter(1);

    const incrementAndHide = () => {
        increment()
        close()
    };

    return <div>
        <button onClick={increment}>Increment</button>
        <button onClick={incrementAndHide}>Increment and Hide</button>
    </div>
}

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by SMerdzhanov** [comment]
Great catch @mungojam! We were having a hard time because of that too. Right now we're using a hack-ish workaround but we would love to see this merged.

**Hey @donavon, thank you and the rest of the collaborators on this hook! It's quite useful 👏** 

Most likely you're busy, but this PR seems pretty straight forward. It's been a while, so I'm basically following up to hear back if this will get merged or we should do fork + fix on our own?
